import EnumSkyBlock from "../../util/EnumSkyBlock.js";
import Block from "./block/Block.js";
import * as THREE from "../../../../../../libraries/three.module.js";
import BlockRenderType from "../../util/BlockRenderType.js";

export default class ChunkSection {

    static SIZE = 16;

    constructor(world, chunk, x, y, z) {
        this.world = world;
        this.chunk = chunk;

        this.x = x;
        this.y = y;
        this.z = z;

        // Expanded bounding box to include overlapping models (like beds) and prevent premature culling
        this.boundingBox = new THREE.Box3();
        this.boundingBox.min.x = x * ChunkSection.SIZE - 1;
        this.boundingBox.min.y = y * ChunkSection.SIZE - 1;
        this.boundingBox.min.z = z * ChunkSection.SIZE - 1;
        this.boundingBox.max.x = x * ChunkSection.SIZE + ChunkSection.SIZE + 1;
        this.boundingBox.max.y = y * ChunkSection.SIZE + ChunkSection.SIZE + 1;
        this.boundingBox.max.z = z * ChunkSection.SIZE + ChunkSection.SIZE + 1;

        this.group = new THREE.Object3D();
        this.group.matrixAutoUpdate = false;
        this.isModified = true;
        this.inUpdateQueue = false;
        this.lastBuiltLOD = null;

        this.blocks = new Uint16Array(4096);
        this.blocksData = new Uint8Array(4096);
        this.blockLight = new Uint8Array(4096);
        this.skyLight = new Uint8Array(4096);
        this.empty = true;
        this.emptyVerified = false;
    }

    render() {

    }

    rebuild(renderer) {
        this.isModified = false;
        
        const world = this.world;
        let player = world.minecraft.player;
        let useLOD = false;
        let distSq = 0;
        if (player) {
            let cx = (this.x * ChunkSection.SIZE) + 8;
            let cy = (this.y * ChunkSection.SIZE) + 8;
            let cz = (this.z * ChunkSection.SIZE) + 8;
            distSq = (player.x - cx)**2 + (player.y - cy)**2 + (player.z - cz)**2;
            const playerChunkX=Math.floor(player.x)>>4,playerChunkZ=Math.floor(player.z)>>4;
            const normalDistance=world.minecraft.settings.viewDistance;
            if (world.minecraft.settings.lodRendering !== false &&
                (Math.abs(this.x-playerChunkX)>=normalDistance || Math.abs(this.z-playerChunkZ)>=normalDistance)) {
                useLOD = true;
            }
        }
        
        this.lastBuiltLOD = useLOD;

        this.group.traverse(child => {
            if (child.isMesh) {
                // Only dispose geometry if it's unique to this chunk section (generated by tessellator)
                if (child.geometry && child.userData.isTessellated) {
                    child.geometry.dispose();
                }
                if (child.material && !(child.material.userData && child.material.userData.sharedChunkMaterial)) {
                    // Dispose textures created by CanvasTexture if present
                    if (child.material.map && child.material.map.dispose) {
                        // Only dispose maps created by tessellator, not shared atlas
                        if (child.material.map.isCanvasTexture) child.material.map.dispose();
                    }
                    if (Array.isArray(child.material)) child.material.forEach(m => m.dispose());
                    else child.material.dispose();
                }
            }
        });
        this.group.clear();

        // Nothing to mesh in a section that has never held a block
        if (this.isEmpty()) return;

        renderer.blockRenderer.liquidRenderer.resetCache();

        // Smooth lighting is optional because per-vertex corner AO can make
        // otherwise well-lit blocks look noticeably darker at their corners.
        // The default is off, but the video settings toggle can enable it.
        let ambientOcclusion = !useLOD && renderer.minecraft.settings.ambientOcclusion;
        const br = renderer.blockRenderer;
        let tessellator = br.tessellator;
        const baseTessellator = tessellator;
        
        const tessellators = [
            tessellator, br.foliageTessellator, br.craftingTableTessellator, 
            br.doorTessellator, br.furnaceTessellator, br.chestTessellator, 
            br.fireTessellator, br.portalTessellator, br.glintTessellator1, br.glintTessellator2
        ];
        for (let t of br.textureTessellators.values()) tessellators.push(t);

        // Pre-fetch neighboring chunks to speed up block lookups at boundaries
        const nChunks = {
            center: this.chunk,
            east:  world.chunks.get((this.x + 1) + "," + this.z),
            west:  world.chunks.get((this.x - 1) + "," + this.z),
            north: world.chunks.get(this.x + "," + (this.z - 1)),
            south: world.chunks.get(this.x + "," + (this.z + 1)),
            up:    this.y < 7 ? this.chunk.sections[this.y + 1] : null,
            down:  this.y > 0 ? this.chunk.sections[this.y - 1] : null
        };

        const isOpaque = (tx, ty, tz) => {
            let id = 0;
            const relX = tx - (this.x << 4);
            const relY = ty;
            const relZ = tz - (this.z << 4);

            // Fast local/neighbor lookup without hitting world.getBlockAt map
            if (relX >= 0 && relX < 16 && relZ >= 0 && relZ < 16 && relY >= 0 && relY < 128) {
                id = this.chunk.getBlockAt(relX, relY, relZ);
            } else {
                // Check pre-fetched neighbors
                let nChunk = null;
                if (relX < 0) nChunk = nChunks.west;
                else if (relX >= 16) nChunk = nChunks.east;
                else if (relZ < 0) nChunk = nChunks.north;
                else if (relZ >= 16) nChunk = nChunks.south;

                if (nChunk && nChunk.loaded) {
                    id = nChunk.getBlockAt(relX & 15, relY, relZ & 15);
                } else {
                    // Fallback for distant chunks
                    id = world.getBlockAt(tx, ty, tz);
                }
            }
            
            if (id === 0) return false;
            let b = Block.getById(id);
            return b && b.isSolid() && !b.isTranslucent();
        };

        for (let i = 0; i < 2; i++) {
            let isTranslucentRenderPhase = i === 1;
            tessellators.forEach(t => t.startDrawing());

            for (let x = 0; x < ChunkSection.SIZE; x++) {
                for (let z = 0; z < ChunkSection.SIZE; z++) {
                    for (let y = 0; y < ChunkSection.SIZE; y++) {
                        let typeId = this.getBlockAt(x, y, z);
                        if (typeId === 0) continue;

                        let block = Block.getById(typeId);
                        if (!block) {
                            const key = typeId + ":" + (this.x * ChunkSection.SIZE + x) + "," + (this.y * ChunkSection.SIZE + y) + "," + (this.z * ChunkSection.SIZE + z);
                            if (this._lastUnknownBlockKey !== key) {
                                this._lastUnknownBlockKey = key;
                                console.warn("Skipping unknown block id during chunk rebuild", key);
                            }
                            continue;
                        }
                        if (block.isTranslucent() !== isTranslucentRenderPhase) continue;

                        let absoluteX = this.x * ChunkSection.SIZE + x;
                        let absoluteY = this.y * ChunkSection.SIZE + y;
                        let absoluteZ = this.z * ChunkSection.SIZE + z;

                        // OPTIMIZATION: Visibility Culling
                        // If block is solid/opaque, skip it if all 6 neighbors are also opaque
                        if (block.isSolid() && !block.isTranslucent()) {
                            let occluded = 
                                isOpaque(absoluteX + 1, absoluteY, absoluteZ) &&
                                isOpaque(absoluteX - 1, absoluteY, absoluteZ) &&
                                isOpaque(absoluteX, absoluteY + 1, absoluteZ) &&
                                isOpaque(absoluteX, absoluteY - 1, absoluteZ) &&
                                isOpaque(absoluteX, absoluteY, absoluteZ + 1) &&
                                isOpaque(absoluteX, absoluteY, absoluteZ - 1);
                            
                            if (occluded) continue;
                        }

                        if (block.getRenderType() === BlockRenderType.CROSS && distSq >= 4096) continue;
                        if (block.getRenderType() === BlockRenderType.FENCE && distSq >= 4096) continue;

                        try {
                            renderer.blockRenderer.renderBlock(world, block, ambientOcclusion, absoluteX, absoluteY, absoluteZ, useLOD, distSq, this.group);
                        } catch (e) {
                            // A single bad block renderer must not leave the whole
                            // section empty. This was most visible in the Nether:
                            // rebuild() clears the old mesh first, so one exception
                            // made a complete chunk section look "corrupted" and
                            // invisible. Reset the active tessellator and keep going.
                            br.tessellator = baseTessellator;
                            const key = typeId + ":" + absoluteX + "," + absoluteY + "," + absoluteZ;
                            if (this._lastBlockRenderErrorKey !== key) {
                                this._lastBlockRenderErrorKey = key;
                                console.warn("Skipped block during chunk rebuild", key, e);
                            }
                        }
                    }
                }
            }

            tessellators.forEach(t => {
                t.setTransparent(isTranslucentRenderPhase);
                if (t.isLeafTessellator) {
                    t.material.alphaTest = (world.minecraft.settings.optimizedLeaves && !isTranslucentRenderPhase) ? 0.0 : 0.1;
                }
            });

            tessellators.forEach(t => {
                try {
                    t.draw(this.group, true);
                } catch (e) {
                    console.warn("Skipped tessellator draw during chunk rebuild", this.x + "," + this.y + "," + this.z, e);
                }
            });
            br.tessellator = baseTessellator;
        }
    }

    getBlockAt(x, y, z) {
        if (this.empty) return 0;
        let index = y << 8 | z << 4 | x;
        return this.blocks[index];
    }

    getBlockDataAt(x, y, z) {
        if (this.empty) return 0;
        let index = y << 8 | z << 4 | x;
        return this.blocksData[index];
    }

    setBlockAt(x, y, z, typeId) {
        let index = y << 8 | z << 4 | x;
        this.blocks[index] = typeId;
        this.isModified = true;

        if (this.empty && typeId !== 0) {
            this.empty = false;
            this.emptyVerified = true;
        }
    }

    setBlockDataAt(x, y, z, data) {
        let index = y << 8 | z << 4 | x;
        this.blocksData[index] = data;
        this.isModified = true;
    }

    setLightAt(sourceType, x, y, z, level) {
        let index = (y << 8) | (z << 4) | x;

        if (sourceType === EnumSkyBlock.SKY) {
            if (this.skyLight[index] === level) return;
            this.skyLight[index] = level;
        } else {
            if (this.blockLight[index] === level) return;
            this.blockLight[index] = level;
        }

        this.isModified = true;
    }

    getTotalLightAt(x, y, z) {
        let index = y << 8 | z << 4 | x;
        let skyLight = this.skyLight[index] - this.world.skylightSubtracted;
        let blockLight = this.blockLight[index];
        if (blockLight > skyLight) {
            skyLight = blockLight;
        }
        return skyLight;
    }

    getLightAt(sourceType, x, y, z) {
        let index = y << 8 | z << 4 | x;
        if (sourceType === EnumSkyBlock.SKY) {
            return this.skyLight[index];
        }
        if (sourceType === EnumSkyBlock.BLOCK) {
            return this.blockLight[index];
        }
        return 0;
    }

    isEmpty() {
        if (!this.empty) return false;
        if (this.emptyVerified) return true;
        // Optimization: Use 32-bit views for 4x faster empty scanning
        const view = new Uint32Array(this.blocks.buffer, this.blocks.byteOffset, this.blocks.length / 2);
        for (let i = 0; i < view.length; i++) {
            if (view[i] !== 0) {
                this.empty = false;
                return false;
            }
        }
        this.emptyVerified = true;
        return true;
    }
}
